#!/usr/bin/env python
# !/Users/llamicron/python_env/bin/python
from i.i import I
import argparse

i = I(file="/Users/llamicron/.i")

parser = argparse.ArgumentParser(description="Connect to servers")
parser.add_argument(
    "command",
    action="store",
    choices=["list", "connect", "add", "remove"],
    type=str,
    help="Command to run. Options are ['list', 'connect', 'add', 'remove']",
    metavar="command"
)
parser.add_argument(
    "-f",
    help="Find a server",
    dest="find",
    metavar="find"
)
parser.add_argument(
    "-n",
    help="Name of server to connect to, eg. 'i connect -n [server_name]'",
    dest="connect_to",
    metavar="connect to"
)
args = parser.parse_args()

if args.command == "list":
    if args.find:
        print(i.find(args.find).table)
    else:
        print(i.server_table().table)

if args.command == "connect":
    if args.connect_to:
        server_name = args.connect_to
    else:
        server_name = raw_input("Server name: ")
    i.connect(server_name)
